"use client";

// shadcn/ui "separator" (new-york-v4) — synced from github.com/shadcn-ui/ui@98a1fe67b439.
// Generated by packages/ui/scripts/sync-shadcn.mjs. Edit the script's patches, not this file.

import * as React from "react";
import { cn } from "../lib/utils";
import { Separator as SeparatorPrimitive } from "radix-ui";

function Separator({
  className,
  orientation = "horizontal",
  decorative = true,
  ...props
}: React.ComponentProps<typeof SeparatorPrimitive.Root>) {
  return (
    <SeparatorPrimitive.Root
      data-slot="separator"
      decorative={decorative}
      orientation={orientation}
      className={cn(
        "shrink-0 bg-border data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-px",
        className,
      )}
      {...props}
    />
  );
}

export { Separator };
