// shadcn/ui "skeleton" (new-york-v4) — synced from github.com/shadcn-ui/ui@98a1fe67b439.
// Generated by packages/ui/scripts/sync-shadcn.mjs. Edit the script's patches, not this file.

import { cn } from "../lib/utils";

function Skeleton({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="skeleton"
      className={cn("animate-pulse rounded-md bg-accent", className)}
      {...props}
    />
  );
}

export { Skeleton };
